### ISSUE TITLE
Contributor instructions and better project setup

### ISSUE THREAD

**Issue by VildMedPap** [oleksiybondar/hyperion#1]
Hi @oleksiybondar,

I saw your [Linkedin post](https://www.linkedin.com/posts/oleksiy-bondar-a353871b9_introducing-hyperion-testing-framework-activity-7093293937292894208-h1nf/) where you said:

> "This is more than a project; it's a community-driven mission to simplify and enhance automation testing. Your ideas, feedback, and contributions can make a difference. Thank you for being part of this journey. Together, we'll build something amazing."

I believe your project could benefit from being prepared for open-source contributions. Here's what you might consider adding:
1. `CONTRIBUTING.md`: Instructions on how to contribute, including how to submit pull requests, follow coding standards, and set up a development environment.
2. Issue templates: Pre-made forms for common issues, so contributors can easily provide the information needed.
3. Pull request template: A guide to help contributors provide the necessary details for a successful pull request.
4. Automated testing and linting: For example, using GitHub Actions.
5. Configurations for linters and formatters: Files to set up linting / formatting tools (e.g. like `mypy`, `black`, and `ruff`).
6. Dependency management: A way to handle dependencies, perhaps through a tool like `poetry`.
7. `CHANGELOG.md`: A record of changes for each commit, version, or release.

If you choose `poetry` for dependency management and the linting/formatting tools listed above, you'll only need the `pyproject.toml` file for configuration (which you by the way misspelled as `pyprohect.toml`).

Setting up these foundations can attract many who are willing to help develop your project.

**Comment by oleksiybondar** [comment]
Hi @VildMedPap 

Thanx for your suggestion, I added `mypy`, `black`, `ruff`,as you suggested,  support with pre-commit  and set up actions which also additionally(in case if contributor did not set pre-commit hooks) checks styles and run tests(only web for now to check basic Page Object harness).
Also I added a needed `md` files and templates, but those are very basic at the moment,  as I don't really have much of requirements at the moment.
Will update them in future.

Fell free to try the framework, but please note there are a lot of things are planned, and this is a page object harness prove of concept, and it does not have advanced selenium/playwright/appium at the moment. Extra features will be coming in short future.
